### ISSUE TITLE
[Feature Request] [SuperPins] Keep pinned tabs at the top and not scrool together with normal tabs  (feature introduced in 1.7.3b)

### ISSUE THREAD

**Issue by poulpor** [JLBlk/Zen-Themes#76]
**The related Mod/Theme:** SuperPins

**Your Enhancement Suggestion/Feature Request:** would it be possible to revert this feature and keep the pinned tabs on top even when scrolling through normal tabs? 

Pet that cute blepping cat for me! :)

![Image](https://github.com/user-attachments/assets/dbb63e49-0635-4548-be8e-49ab6a001301)

**Comment by poulpor** [comment]
In the meantime, I rely on the css code written and shared by mr.bill on zen browser discord, it still works in zen browser 1.7.6b. Copy/paste it in your userChrome.css

`/* ------ Pins Scroll Fix ------ */
/* NOTE: This will glitch out on smaller window sizes. YMMV so dont expect perfection */
#zen-browser-tabs-wrapper {
  display: flex;
  flex-direction: column;
  overflow-y: hidden;
}

#vertical-pinned-tabs-container {
  max-height: calc(5 * var(--tabstrip-min-height) + var(--space-large)) !important; /* change the 5 to whatever you want lol */
  overflow-y: auto !important;
}

#tabbrowser-arrowscrollbox {
  overflow-y: auto;
}`

**Comment by CosmoCreeper** [comment]
I have found a fix that will work on all window sizes, however, I just can't seem to find a way to set the background of the pinned tabs to remain the same as the rest of the sidebar. (so that you don't see the tabs underneath the pinned tabs as you are scrolling through them.)

If you have any suggestions, please let me know!

**Comment by CosmoCreeper** [comment]
Update:
Here is the code I found!
```
#zen-browser-tabs-container, #vertical-pinned-tabs-container, #zen-tabs-wrapper {
    position: static !important;
}

#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
    z-index: 5;
    width: 100%;
}

#tabbrowser-arrowscrollbox {
    position: relative !important;
}
```

**Comment by poulpor** [comment]
Thank you very much for your work on this feature, it behaves nicely even if tabs are visible underneath the pinned ones, as you mentioned! Does the separator you mentioned in your pull request [#96](https://github.com/JLBlk/Zen-Themes/pull/96) solve the problem?
Again, thank you very much for your time, I suppose Zen is not an easy project to follow because of its sudden changes, but I love it!

**Comment by CosmoCreeper** [comment]
No, it is not fixed in #96 yet. I was waiting to see if maybe you knew how to change the background to look like the rest of the sidebar. Once that is figured out, I'll tack it onto #96.

**Comment by CosmoCreeper** [comment]
Just fixed! #96 now has an implementation (using a completely different method than what I showed you) of keeping pinned tabs at the top. It does not require any sort of background property due to the way it is set up.

If you would like to try it now, you can copy the code from my pull request or use the following code (works with tab groups as well):

```css
#zen-browser-tabs-container {
    height: 100% !important;
}

#tabbrowser-arrowscrollbox {
    height: 100% !important;
}

#tabbrowser-arrowscrollbox > .zen-workspace-tabs-section {
    overflow-y: auto !important;
    /* Calculate the height of the bottom workspace section. */
    max-height: calc(100% - 43px) !important;
    box-sizing: border-box !important;
    padding-bottom: 60px !important;
}

/* In case workspace indicator is not visible. */
@media (not (-moz-bool-pref: "zen.workspaces.show-workspace-indicator")) {
    #tabbrowser-arrowscrollbox > .zen-workspace-tabs-section {
        max-height: calc(100% - 5px) !important;
    }
}

#zen-tabs-wrapper {
    overflow: hidden !important;
}

/* Ensure tab-groups never shrink. */
tab-group {
    flex: 0 0 auto !important;
}
```
